### ISSUE TITLE
Minor Server Call Issues

### ISSUE THREAD

**Issue by Cavonte** [SOEN341/Schedule-Builder#55]
I have noticed something recently. 
When username is changed, the cookies are not affected. And If i am right they are used for the subsequent server calls. (such as password change for instance)

To replicate this go into the account page change the username and then try to change the password.

If the issues was solved, just close the issue

**Comment by Cavonte** [comment]
Also in the same scope, when you create a new account, the preferences server calls will all fail in their first try since it appears that the cookies are set after they have been modified one. I could fixed this on my end putting a default value in the server call when its empty, but I figured I would let you  guys know.

**Comment by SeanMarcoux** [comment]
That is strange. I'm pretty sure I did update the cookie after the username is changed. Not sure what the preferences issue was and we couldn't later replicate it. We'll have to look into it more to see

**Comment by SeanMarcoux** [comment]
So I'm going to update this task because the issues seem to actually be on the back-end. Also, I don't have the preferences problem so I'll assume it's been fixed. Here's a list of minor issues with server calls:
1) After updating my username, I could not log in with the new username (old username didn't work either)
3) /addadminsection returns "" for the sectionid and even if it returns success: 'true', later /sectioncourse calls do not return the new section
4) /addadmincourse has the same issues as /addadminsection
5)  /editsection does not let you change the section name (ex: UJ, UX, etc) and it should let you do that

**Comment by SeanMarcoux** [comment]
6) Apparently /register doesn't check if there was already a user registered with the same e-mail, but if you try to register with a different username and the same e-mail, it doesn't let you. I updated the front-end to communicate this, so this doesn't really need to be fixed. We just pretend it does check that and we force the user to enter a different e-mail. Fixing this is optional

**Comment by SeanMarcoux** [comment]
Actually, on the subject of 6, it SHOULD check and make sure no other user has the same e-mail, so it's good that it acts this way. If anything, fixing 6 would mean making sure it does check this properly

**Comment by Cavonte** [comment]
1)Still have to figure it out.
3)I have no explanation as to why it is not working on your end. Added a new course Comp 250, added 2 new sections and then edited all 3 of them. The output of the script did not have any empty value, and I checked the /section and /courses page to be sure the information was updated.
4) ^ Tried with 2 new courses to be sure.
5) fixed. the code I put was meant to check if the id existed beforehand, we dont really need it. It was removed.
6)fixed, however the ui thinks it is still an username duplication. If it was not checking it well it is checking it now.

**Comment by SeanMarcoux** [comment]
Could it be something to do with how we set up the databases? Did you use the finaldbfile.sql as the source?

**Comment by Cavonte** [comment]
My last db update was on the finaldb one.

**Comment by SeanMarcoux** [comment]
No idea why it wouldn't work on my end if it does for you, then

**Comment by Cavonte** [comment]
@SeanMarcoux   Update this if you are still having issues. 

I think I might have found  why once you change the username, login does not work anymore.
When you register, your username is used to create a value that is then used to encrypt the password. 
(see register.blade.php)
Now the issue is that when you login, it does the same thing and compare the provided password(created with username from the form) and the encrypted password in the db. 
This creates a problem when you change your username because at your next attempt the new username will be used to create a password to test against the db. Hence the error. (see login.blade.php)
Were you to use the old username , it would not work either because the server call is going to return username not found.
If it is not this, then I dont know what else. @SeanMarcoux 
@sihx thought ? 

Also @sihx is this supposed to be commented out in the register page ?
// if(Hash::needsRehash($encryptedPassword)){
     //     $encryptedPassword = Hash::make('$password');
     // }

**Comment by SeanMarcoux** [comment]
Yes I am still having the issues for adding courses and sections. I'm really no sure why. If someone else can check if they have the issues too, that would be nice

**Comment by SeanMarcoux** [comment]
Can we just completely remove the password stuff from the returned JSON for logging in and registering. There's no reason to return it and it seems like a security concern

**Comment by Cavonte** [comment]
I pushed en export of my db, try working with this one it was the one I was working with.
You can even see the courses/sections I added.

The password is for testing puposes, they will be removed.

**Comment by sihx** [comment]
@Cavonte the commented code can be removed if you want, we are not using it. As for the username I can fix the issue

**Comment by SeanMarcoux** [comment]
I switched to your sql and I definitely still get a blank courseID back when I add a course

**Comment by SeanMarcoux** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8944462/14408157/199a2580-feb6-11e5-93d2-cc0c63eb62dd.png)

**Comment by SeanMarcoux** [comment]
It's weird because I can see the ones you added, but then mine don't show up

**Comment by SeanMarcoux** [comment]
So I'm taking a look at the code and I'm not sure how you got it to work on your end.
I see: $courseId= 'null';
And that is what's entered into the database. I never see anywhere where the value is changed

**Comment by Cavonte** [comment]
Its null so that the db can increment it automatically to the next available unique course id.

We could hardcode it. But we would have to keep track of what the current id is.

Envoyé depuis un mobile Samsung

<div>-------- Message d'origine --------</div><div>De : Sean Marcoux <notifications@github.com> </div><div>Date :04/10/2016  1:05 AM  (GMT-05:00) </div><div>À : SOEN341/Schedule-Builder <Schedule-Builder@noreply.github.com> </div><div>Cc : Bruce Edouard Brazier <edouard.12@live.ca> </div><div>Objet : Re: [SOEN341/Schedule-Builder] Minor Server Call Issues (#55) </div><div>
</div>

So I'm taking a look at the code and I'm not sure how you got it to work on your end.
I see: $courseId= 'null';
And that is what's entered into the database. I never see anywhere where the value is changed

---

**Comment by SeanMarcoux** [comment]
Ok well Emili tested it and she says it worked for her on her end, so I'm going to say this bug is fixed. Not sure why it's not working on my end, but it works for everyone else
